apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: tripinsights-api
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
