apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: tripinsights-api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrypvp6623.azurecr.io/tripinsights/userprofile:1.0
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: PORT
            value: "8080"
          - name: CONFIG_FILES_PATH
            value: /secrets
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "trip-insigsts-key-vault"
