apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: tripinsights-api
  labels:
    app: user-java
spec:
  type: ClusterIP
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
