apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: tripinsights-api
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrypvp6623.azurecr.io/tripinsights/user-java:1.0
        ports:
          - containerPort: 8080
            name: http
        envFrom:
          - secretRef:
              name: tripinsights-db-secret
        env:
          - name: PORT
            value: "8080"
