apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: tripinsights-api
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrypvp6623.azurecr.io/tripinsights/poi:1.0
        ports:
          - containerPort: 8080
            name: http
          - containerPort: 443
            name: https
        envFrom:
          - secretRef:
              name: tripinsights-db-secret
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: WEB_PORT
            value: "8080"