kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trip-deny-privileged-clusterrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - trip-deny-privileged
  verbs:
  - use