kind: Role 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  namespace: tripinsights-api 
  name: secret-reader
rules: 
- apiGroups: [""] # "" indicates the core API group 
  resources: ["secrets"] 
#  verbs: ["get", "list"]
  verbs: ["list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-service-account-secret-access
  namespace: tripinsights-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  namespace: tripinsights-api
  name: apidev