apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: tripinsights-api
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: trips