apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: tripinsights-web
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: tripviewer